apiVersion: v1
kind: ConfigMap
metadata:
  name: load-tester-config
  namespace: geth-dev
data:
  RPC_URL: "http://geth-dev-0.geth-dev.geth-dev.svc.cluster.local:8545"
  NUM_ACCOUNTS: "20"
  TXS_PER_BATCH: "100"
  BATCH_INTERVAL: "10"
  TX_VALUE_WEI: "1000000000000000" # 0.001 ETH
  GAS_LIMIT: "21000"
  CONTINUOUS: "true"
  TOTAL_BATCHES: "10"
  METRICS_PORT: "8000"
  FUND_AMOUNT_ETHER: "1.0"
